- name: Get a list of all PVCs from any namespace
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
  register: pvc_list

- name: "Filter the PVC list to only show the PVCs with the storageClassName {{ old_storage_class }}"
  set_fact:
    old_storage_class_pvc: "{{ pvc_list.resources | selectattr('spec.storageClassName', 'equalto', old_storage_class) |  list }}"
  
- name: "Filter the PVC list to only show the PVCs with the name equal to {{ pvc_name }}"
  set_fact:
    filter_pvc: "{{ old_storage_class_pvc | selectattr('metadata.name', 'equalto', pvc_name) | list }}"

- name: "Display the PVC list array"
  debug:
    msg: "{{ filter_pvc }}"

- name: "Get a list of all pods from namespaces found in filter_pvc"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ item.metadata.namespace }}"
  register: pod_list
  loop: "{{ filter_pvc }}"

- name: Display pod_list
  debug:
    msg: >-
      {{
        pod_list.results[0].resources | selectattr('spec.volumes', 'defined') | selectattr('spec.volumes', 'search', pvc_name) | map(attribute='metadata.namespace') | list
      }}
    # msg: "{{ pod_list.results[0].resources | map(attribute='metadata.name') | zip_longest(pod_list.results[0].resources | map(attribute='metadata.namespace'), pod_list.results[0].resources | subelements('spec.volumes.persistentVolumeClaim.claimName'), fillvalue='') | list }}"
    # msg: "{{ pod_list.results[0].resources | map(attribute='metadata.namespace') | map(attribute='spec.volumes') | list }}
    # msg: "{{ pod_list.results[0].resources | map(attribute='spec') | map() | list }}"
    # msg: "{{ pod_list.results[0].resources | map(attribute='metadata.name') | zip_longest(pod_list.results[0].resources | map(attribute='metadata.namespace', pod_list.results[0].resources | selectattr('spec.volumes', 'defined') | selectattr('spec.volumes', 'selectattr', 'persistentVolumeClaim.claimName', 'equalto', pvc_name), fillvalue='') | list }}"
    # msg: "{{ pod_list.results | selectattr('resources.spec.volumes', 'defined') | selectattr('resources.spec.volumes', 'selectattr', 'persistentVolumeClaim.claimName', 'equalto', 'pipeline-pvc') | list }}"

# go through pod list
# check if any pod has pvc named pvc_name under pvc
# if it is then remove the namespace and pvc_name from the list
# if it stays it means the pvc is in use
# add the pvcs in use to a list and display to runner
# - name:
#   set_fact:
#     pod_with_pvc_name: "{{ pod_list.results | selectattr('resources.spec.volumes', 'defined') | selectattr('spec.volumes', 'selectattr', 'persistentVolumeClaim.claimName', 'equalto', pvc_name) | map(attribute='metadata.name') | list }}"

# - name: echo the found pod
#   debug:
#     msg: "{{ pod_with_pvc_name }}"

# - name: Filter out PVCs associated with Pods from PVC list
#   set_fact:
#     pvc_definitions: "{{ filter_pvc | selectattr('name', 'not in', pvc_in_use) | list }}"

# - name: debug pvc_definitions value
#   debug:
#     msg: "{{ pvc_definitions }}"

- name: "Fail if there are zero {{ old_storage_class }} PVCs"
  fail: 
    msg: "Purposefully failing because no PVCs with {{ old_storage_class }} exist."
  when: "{{ filter_pvc | length == 0 }}"
