- name: Get a list of all PVCs from any namespace
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
  register: pvc_list

- name: Filter the pvc List to only show the PVCs with the storageClassName 'ocs-storagecluster-cephfs'
  set_fact:
    cephfs_pvc: "{{ pvc_list.resources | selectattr('spec.storageClassName', 'equalto', 'ocs-storagecluster-cephfs') |  list }}"
  
- name: Filter the PVC list to only show the PVCs with the name containing 'pipeline'.
  set_fact:
    filter_pvc: "{{ cephfs_pvc | selectattr('metadata.name', 'equalto', 'pipeline-testing-haha') | list }}"

- name: Display the PVC list array
  debug:
    msg: "{{ filter_pvc }}"

- name: Good news, failing if there are zero cephfs PVCs
  fail: 
    msg: "Purposefully failing because no PVCs with cephfs exist."
  when: "{{ filter_pvc | length == 0 }}"
