- name: Get a list of all PVCs from any namespace
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
  register: pvc_list

- name: Filter the pvc List
  set_fact:
    cephfs_pvc: "{{ pvc_list.resources | selectattr('spec.storageClassName', 'equalto', 'ocs-storagecluster-cephfs') | list }}"
  
- name: more filter
  set_fact:
    filter_pvc: "{{ cephfs_pvc | selectattr('metadata.name', 'search', 'pipeline') | list }}"

- name: Display pvc List
  debug:
    msg: "{{ filter_pvc }}"

# if filter_pvc contains 0, exit
- name: count pvc List
  set_fact:
    cephfs_count: "{{ filter_pvc | length > 0 }}"

- name: Fail if cephfs_count is 0
  fail: 
    msg: "Purposefully failing because no PVCs with cephfs exist."
  when: cephfs_count
