- name: Get a list of all PVCs from any namespace
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
  register: pvc_list

# - name: "Filter the PVC list to only show the PVCs with the storageClassName {{ old_storage_class }} and name equal to {{ pvc_name }}"
#   set_fact:
#     old_storage_class_pvc: "{{ pvc_list.resources | selectattr('spec.storageClassName', 'equalto', old_storage_class) |  list }}"
  
# - name: "Filter the PVC list to only show the PVCs with the name equal to {{ pvc_name }}"
#   set_fact:
#     filter_pvc: "{{ old_storage_class_pvc | selectattr('metadata.name', 'equalto', pvc_name) | list }}"

- name: "Filter the PVC list to only show the PVCs with the name equal to {{ pvc_name }}"
  set_fact:
    filter_pvc: "{{ pvc_list.resources | selectattr('spec.storageClassName', 'equalto', old_storage_class) | selectattr('metadata.name', 'equalto', pvc_name) | list }}"

- name: "Display the PVC list array"
  debug:
    msg: "{{ filter_pvc }}"

# go through pod list
# check if any pod has pvc named pvc_name under pvc
# if it is then remove the namespace and pvc_name from the list
# if it stays it means the pvc is in use
# add the pvcs in use to a list and display to runner

- name: "Get a list of all pods from namespaces found in filter_pvc"
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ item.metadata.namespace }}"
  register: pod_list
  loop: "{{ filter_pvc }}"

- name: debug pod_list
  debug:
    msg: "{{ pod_list }}"

- name: Find namespaces using PVC
  set_fact:
    namespaces_using_pvc: "{{ pod_list.results | map(attribute='resources') | flatten | selectattr('spec.volumes', 'defined') | selectattr('spec.volumes', 'search', pvc_name) | map(attribute='metadata.namespace') | list }}"

- name: Display namespaces using PVC
  debug:
    msg: "{{ namespaces_using_pvc }}"

- name: Prompt runner which PVCs cannot be deleted
  debug:
    msg: "Not deleting {{ pvc_name }} in namespace {{ item.metadata.namespace }} -- Currently being used by a pod."
  loop: "{{ filter_pvc | selectattr('metadata.namespace', 'in', namespaces_using_pvc) | list }}"

- name: Filter out PVCs associated with Pods from PVC list
  set_fact:
    pvc_definitions: "{{ filter_pvc | rejectattr('metadata.namespace', 'in', namespaces_using_pvc) | list }}"

- name: debug pvc_definitions value
  debug:
    msg: "{{ pvc_definitions }}"

- name: "Fail if there are zero {{ old_storage_class }} PVCs to update"
  fail:
    msg: "Purposefully failing because no PVCs with {{ old_storage_class }} exist."
  when: "{{ pvc_definitions | length == 0 }}"
