- name: Get a list of all PVCs from any namespace
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
  register: pvc_list

- name: Filter the pvc List
  set_fact:
    cephfs_pvc: "{{ pvc_list.resources | selectattr('metadata.name', 'search', 'pipeline'),  pvc_list.resources | selectattr('spec.storageClassName', 'equalto', 'ocs-storagecluster-cephfs') | list }}"
  
# - name: Only show the name, namespace, and storageclass
#   set_fact:
#     filter_pvc: "{{ cephfs_pvc | map(attribute='metadata'), cephfs_pvc | map(attribute='name') | map(attribute='metadata.namespace'), cephfs_pvc | map(attribute='spec.storageClassName') | list }}"

- name: Display pvc List
  debug:
    msg: "{{ cephfs_pvc }}"