- name: Get a list of all PVCs from any namespace
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
  register: pvc_list

- name: Filter the pvc List
  set_fact:
    cephfs_pvc: "{{ pvc_list.resources | selectattr('spec.storageClassName', 'equalto', 'ocs-storagecluster-cephfs') | list }}"

- name: Display pvc List
  debug:
    var: cephfs_pvc