- name: Get a list of all PVCs from any namespace
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
  register: pvc_list

- name: "Filter the PVC list to only show the PVCs with the storageClassName {{ old_storage_class }}"
  set_fact:
    old_storage_class_pvc: "{{ pvc_list.resources | selectattr('spec.storageClassName', 'equalto', old_storage_class) |  list }}"
  
- name: "Filter the PVC list to only show the PVCs with the name containing {{ pvc_name }}"
  set_fact:
    filter_pvc: "{{ old_storage_class_pvc | selectattr('metadata.name', 'equalto', pvc_name) | list }}"

- name: "Display the PVC list array"
  debug:
    msg: "{{ filter_pvc }}"

- name: "Fail if there are zero {{ old_storage_class }} PVCs"
  fail: 
    msg: "Purposefully failing because no PVCs with {{ old_storage_class }} exist."
  when: "{{ filter_pvc | length == 0 }}"
