# TODO: use loop to go through filter_pvc fact and delete PVC then re-create using Jinja template.

# - name: List through loop
#   debug:
#     msg: "{{ item.metadata.name }} {{ item.metadata.namespace}} {{ item.spec.resources.requests.storage }}"
#   loop: "{{ filter_pvc }}"

- name: Delete designated PVC by name and namespace.
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: "{{ item.metadata.namespace }}"
    name: "{{ item.metadata.name }}"
  loop: "{{ pvc_definitions }}"

- name: Re-create designated PVC by name and namespace using pvc-template.
  kubernetes.core.k8s:
    state: present
    template:
      path: 'pvc-template.yml.j2'
  loop: "{{ pvc_definitions }}"